### ISSUE TITLE
Units on timeseries `.plot` and `.quantity` are inconsistent

### ISSUE THREAD

**Issue by wtbarnes** [TCDSolar/stixpy#104]
When I extract a quantity from a STIX quicklook lightcurve using `.quantity`, the units are in `ct`. However, when I visualize that same data with `peek` or `plot`, the y-label says the units are `ct s-1 keV-1`. The latter appears to be hardcoded in the `plot` method.

**Comment by samaloney** [comment]
Thanks for reporting, yes the raw data is `ct` but often for plotting want it in `ct s-1 keV-1` or even `ct s-1 keV-1 cm-2`. I'm not sure what to do here as I dont think there's a way to support different units in Timeseries? I guess as a hack I could create addition columns for the different units `counts`: `ct`, `count_rate`: `ct s-1`,  `differential_count_rate`:  `ct s-1 keV-1`,
`differential_count_flux`: `ct s-1 keV-1 cm-2`.

**Comment by samaloney** [comment]
There is also a bug in the code which I will fix where the units are hardcoded to be `ct` but the data are converted to `ct s-1 keV-1` during loading.
