### ISSUE TITLE
Compressed pixel data plotted in units of cts/cs/keV with plot_timeseries()

### ISSUE THREAD

**Issue by hannahc243** [TCDSolar/stixpy#129]
Compressed pixel data is currently plotted in units of cts/cs/keV using the plot_timeseries() method, whereas quicklook data is in units of cts/s/keV. It might be more straightforward to have them in the same units or to have the option to plot in different units (e.g. cts/s/keV) using a kwarg. Is there a particular reason for plotting in cts/cs/keV currently?

**Comment by samaloney** [comment]
Thanks for raising the issue essentially `cs` is the native time unit in the file and currently don't do any conversion. It should be pretty straightforward to use `.to(u.s)` somewhere to change back to seconds.
