### ISSUE TITLE
plot_timeseries only plot 0th pixel and detector rather than summing over all pixels/detectors

### ISSUE THREAD

**Issue by hayesla** [TCDSolar/stixpy#49]
when using the `plot_timeseries()` method on `stixpy.science.CompressedPixelData` it only plots the 0th index of the detector and pixel indices rather than summing over them like it does for the `plot_spectrogram`

https://github.com/samaloney/stixpy/blob/e41582be8b6d4838fa25ef9cb81771cc955d8fc4/stixpy/science.py#L213

what you probably want is to sum over them in the `get_data()` part, or all both the detector and pixel indices to be passed. To be consistent I would think it should be the same as the spectrogram for the moment (i.e. sum over all pixels and detectors) - functionality from #48  would help

thoughts?

**Comment by samaloney** [comment]
Yea I guess the only problem I see is the BKG and CFL detectors but I guess not huge deal

**Comment by samaloney** [comment]
So the default now includes all detectors need to improve the display to let user know which detectors though.

```
cpd = Product('https://pub099.cs.technik.fhnw.ch/fits/L1/2022/02/15/SCI/solo_L1_stix-sci-xray-cpd_20220215T214529-20220215T222336_V02_2202154670-60563.fits')
cpd.plot_timeseries()
```
<img width="752" alt="image" src="https://github.com/TCDSolar/stixpy/assets/24570854/6af82860-441e-413c-994f-63cd5ea7f953">

vs

```
cpd.plot_timeseries(detector_indices=[0])
```
<img width="752" alt="image" src="https://github.com/TCDSolar/stixpy/assets/24570854/9151abf4-efe7-493e-b026-72f9dec55ebc">
