### ISSUE TITLE
Add CFL to the QL that can be found with Fido

### ISSUE THREAD

**Issue by somusset** [TCDSolar/stixpy#52]
It would be great to also have access to the CFL info with the Fido method (as I could see only the lightcurves, background, variance, spectra and flareflag data products are available for quick look data)

**Comment by samaloney** [comment]
So the CFL data are actually searchable with Fido but the text description is wrong. The CFL is part of the flare flag TM.

```
from sunpy.net import Fido, attrs as a
from stixpy.net import client
query = Fido.search(a.Time('2024-05-01', '2024-05-01'), a.Instrument.stix, a.stix.DataProduct.ql_flareflag)
query
<sunpy.net.fido_factory.UnifiedResponse object at 0x13af0a790>
Results from 1 Provider:

1 Results from the STIXClient:

       Start Time               End Time        Instrument Level DataType DataProduct  Ver  Request ID
----------------------- ----------------------- ---------- ----- -------- ------------ ---- ----------
2024-05-01 00:00:00.000 2024-05-01 23:59:59.999       STIX    L1       QL ql-flareflag V02U
```

but currently there is no product for the flare_flag data.

So need to fix the text description for the `ql_flareflag` DataProduct and then implement a data product for the flare flag data.
