### ISSUE TITLE
STIX Imaging frame

### ISSUE THREAD

**Issue by samaloney** [TCDSolar/stixpy#88]
Have implement the frame but need to:

- [x] check the transformations
- [x] add mapping between WCS and frames so plays nicely with Map
- [x] test reprojection to and from

**Comment by paolomassa** [comment]
Is it already implemented a function for reading the aspect solution from solo_L2_stix-aux-ephemeris fits files? See [stx_create_auxiliary_data.pro](https://github.com/i4Ds/STIX-GSW/blob/master/stix/idl/processing/aux_data/stx_create_auxiliary_data.pro)
